In [1]:
# 라이브러리 임포트
import tensorflow as tf
import pandas as pd

In [2]:
baseball_data = pd.read_csv('./baseball_2015_2019.csv', encoding='CP949')
baseball_data.head()

,날짜,팀,상대팀,홈팀,타석,타수,타점,득점,안타,홈런,도루,도실,희비,볼넷,삼진,병살,잔루율,출루율,타율,승패
0,20150328,HH,NE,T,54,42,4,4,10,0,8,0,1,7,7,0,24,0.352941,0.238095,0.0
1,20150328,NE,HH,B,46,40,5,5,8,2,4,0,0,6,7,1,18,0.304348,0.200000,1.0
2,20150328,KT,LT,T,46,35,8,9,14,2,2,1,1,8,8,1,23,0.511111,0.400000,0.0
3,20150328,LT,KT,B,42,37,12,12,14,2,4,1,0,3,8,1,17,0.439024,0.378378,1.0
4,20150328,LG,HT,T,34,29,1,1,7,0,0,0,0,4,6,2,17,0.333333,0.241379,0.0

In [18]:
baseball_2015 = pd.read_csv('./baseball_2015.csv', encoding='CP949')
baseball_2015.head()

,G_ID,GDAY_DS,T_ID,VS_T_ID,HEADER_NO,TB_SC,PA,AB,RBI,RUN,...,HP,KK,GD,LOB,P_HRA_RT,P_AB_CN,P_HIT_CN,OBP,OOO,win
0,20150328HHNE0,20150328,HH,NE,0,T,54,42,4,4,...,1,7,0,24,0.133333,15,2,0.352941,0.238095,0.0
1,20150328HHNE0,20150328,NE,HH,0,B,46,40,5,5,...,0,7,1,18,0.090909,11,1,0.304348,0.200000,1.0
2,20150328KTLT0,20150328,KT,LT,0,T,46,35,8,9,...,1,8,1,23,0.285714,14,4,0.511111,0.400000,0.0
3,20150328KTLT0,20150328,LT,KT,0,B,42,37,12,12,...,1,8,1,17,0.437500,16,7,0.439024,0.378378,1.0
4,20150328LGHT0,20150328,LG,HT,0,T,34,29,1,1,...,0,6,2,17,0.200000,10,2,0.333333,0.241379,0.0

In [3]:
baseball_2016 = pd.read_csv('./baseball_2016.csv', encoding='CP949')
baseball_2016.head()

,G_ID,GDAY_DS,T_ID,VS_T_ID,HEADER_NO,TB_SC,PA,AB,RBI,RUN,...,HP,KK,GD,LOB,P_HRA_RT,P_AB_CN,P_HIT_CN,OBP,OOO,win
0,20160401HHLG0,20160401,HH,LG,0,T,52.0,46.0,4.0,4.0,...,0.0,10.0,1.0,24.0,0.200000,15,3,0.326531,0.282609,0.0
1,20160401HHLG0,20160401,LG,HH,0,B,47.0,42.0,4.0,5.0,...,0.0,11.0,0.0,15.0,0.333333,12,4,0.282609,0.214286,1.0
2,20160401HTNC0,20160401,HT,NC,0,T,38.0,34.0,3.0,4.0,...,1.0,10.0,1.0,17.0,0.100000,10,1,0.315789,0.235294,0.0
3,20160401HTNC0,20160401,NC,HT,0,B,36.0,30.0,5.0,5.0,...,0.0,9.0,1.0,14.0,0.142857,7,1,0.400000,0.300000,1.0
4,20160401KTSK0,20160401,KT,SK,0,T,42.0,36.0,7.0,8.0,...,1.0,7.0,0.0,17.0,0.285714,7,2,0.380952,0.305556,1.0

In [4]:
baseball_2017 = pd.read_csv('./baseball_2017.csv', encoding='CP949')
baseball_2017.head()

,G_ID,GDAY_DS,T_ID,VS_T_ID,HEADER_NO,TB_SC,PA,AB,RBI,RUN,...,HP,KK,GD,LOB,P_HRA_RT,P_AB_CN,P_HIT_CN,OBP,OOO,win
0,20170331HHOB0,20170331,HH,OB,0,T,33.0,29.0,0.0,0.0,...,0.0,8.0,0.0,11.0,0.000000,4,0,0.218750,0.137931,0.0
1,20170331HHOB0,20170331,OB,HH,0,B,33.0,27.0,3.0,3.0,...,2.0,8.0,0.0,15.0,0.111111,9,1,0.242424,0.148148,1.0
2,20170331HTSS0,20170331,HT,SS,0,T,42.0,34.0,7.0,7.0,...,0.0,5.0,0.0,12.0,0.285714,7,2,0.357143,0.205882,1.0
3,20170331HTSS0,20170331,SS,HT,0,B,33.0,31.0,2.0,2.0,...,0.0,7.0,1.0,8.0,0.000000,3,0,0.250000,0.225806,0.0
4,20170331KTSK0,20170331,KT,SK,0,T,37.0,35.0,3.0,3.0,...,0.0,8.0,1.0,12.0,0.200000,5,1,0.297297,0.257143,1.0

In [5]:
baseball_2018 = pd.read_csv('./baseball_2018.csv', encoding='CP949')
baseball_2018.head()

,G_ID,GDAY_DS,T_ID,VS_T_ID,HEADER_NO,TB_SC,PA,AB,RBI,RUN,...,HP,KK,GD,LOB,P_HRA_RT,P_AB_CN,P_HIT_CN,OBP,OOO,win
0,20180324HHNE0,20180324,HH,NE,0,T,38.0,37.0,2.0,3.0,...,0.0,9.0,0.0,16.0,0.230769,13,3,0.368421,0.351351,0.0
1,20180324HHNE0,20180324,NE,HH,0,B,41.0,37.0,5.0,6.0,...,0.0,10.0,0.0,26.0,0.235294,17,4,0.390244,0.324324,1.0
2,20180324KTHT0,20180324,KT,HT,0,T,38.0,37.0,5.0,5.0,...,0.0,9.0,0.0,11.0,0.400000,5,2,0.315789,0.297297,1.0
3,20180324KTHT0,20180324,HT,KT,0,B,43.0,36.0,4.0,4.0,...,2.0,8.0,0.0,25.0,0.272727,11,3,0.390244,0.333333,0.0
4,20180324LGNC0,20180324,LG,NC,0,T,32.0,30.0,2.0,2.0,...,0.0,9.0,1.0,10.0,0.000000,4,0,0.250000,0.233333,0.0

In [6]:
baseball_2019 = pd.read_csv('./baseball_2019.csv', encoding='CP949')
baseball_2019.head()

,G_ID,GDAY_DS,T_ID,VS_T_ID,HEADER_NO,TB_SC,PA,AB,RBI,RUN,...,HP,KK,GD,LOB,P_HRA_RT,P_AB_CN,P_HIT_CN,OBP,OOO,win
0,20190323HHOB0,20190323,HH,OB,0,T,42.0,34.0,4.0,4.0,...,1.0,7.0,2.0,18.0,0.200000,10,2,0.439024,0.352941,0.0
1,20190323HHOB0,20190323,OB,HH,0,B,33.0,28.0,5.0,5.0,...,0.0,3.0,1.0,9.0,0.500000,4,2,0.333333,0.214286,1.0
2,20190323KTSK0,20190323,KT,SK,0,T,39.0,36.0,4.0,4.0,...,0.0,10.0,1.0,21.0,0.200000,10,2,0.307692,0.250000,0.0
3,20190323KTSK0,20190323,SK,KT,0,B,37.0,31.0,6.0,7.0,...,0.0,5.0,1.0,13.0,0.375000,8,3,0.378378,0.258065,1.0
4,20190323LGHT0,20190323,LG,HT,0,T,34.0,31.0,2.0,2.0,...,0.0,12.0,3.0,11.0,0.142857,7,1,0.323529,0.258065,1.0

In [19]:
baseball_data = pd.concat([baseball_2015, baseball_2016,baseball_2017, baseball_2018, baseball_2019])
baseball_data

,G_ID,GDAY_DS,T_ID,VS_T_ID,HEADER_NO,TB_SC,PA,AB,RBI,RUN,...,HP,KK,GD,LOB,P_HRA_RT,P_AB_CN,P_HIT_CN,OBP,OOO,win
0,20150328HHNE0,20150328,HH,NE,0,T,54.0,42.0,4.0,4.0,...,1.0,7.0,0.0,24.0,0.133333,15,2,0.352941,0.238095,0.0
1,20150328HHNE0,20150328,NE,HH,0,B,46.0,40.0,5.0,5.0,...,0.0,7.0,1.0,18.0,0.090909,11,1,0.304348,0.200000,1.0
2,20150328KTLT0,20150328,KT,LT,0,T,46.0,35.0,8.0,9.0,...,1.0,8.0,1.0,23.0,0.285714,14,4,0.511111,0.400000,0.0
3,20150328KTLT0,20150328,LT,KT,0,B,42.0,37.0,12.0,12.0,...,1.0,8.0,1.0,17.0,0.437500,16,7,0.439024,0.378378,1.0
4,20150328LGHT0,20150328,LG,HT,0,T,34.0,29.0,1.0,1.0,...,0.0,6.0,2.0,17.0,0.200000,10,2,0.333333,0.241379,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459,20191023WOOB0,20191023,OB,WO,0,B,37.0,32.0,5.0,6.0,...,0.0,8.0,1.0,13.0,0.285714,7,2,0.351351,0.281250,1.0
1460,20191025OBWO0,20191025,OB,WO,0,T,40.0,35.0,5.0,5.0,...,1.0,11.0,0.0,15.0,0.181818,11,2,0.325000,0.228571,1.0
1461,20191025OBWO0,20191025,WO,OB,0,B,32.0,28.0,0.0,0.0,...,0.0,2.0,1.0,9.0,0.250000,4,1,0.250000,0.142857,0.0
1462,20191026OBWO0,20191026,OB,WO,0,T,50.0,42.0,10.0,11.0,...,1.0,11.0,1.0,24.0,0.437500,16,7,0.428571,0.333333,1.0
1463,20191026OBWO0,20191026,WO,OB,0,B,50.0,44.0,7.0,9.0,...,0.0,4.0,1.0,26.0,0.187500,16,3,0.346939,0.272727,0.0

In [20]:
# 결측치 확인
baseball_data.isnull().any()

G_ID         False
GDAY_DS      False
T_ID         False
VS_T_ID      False
HEADER_NO    False
TB_SC        False
PA           False
AB           False
RBI          False
RUN          False
HIT          False
H2           False
H3           False
HR           False
SB           False
CS           False
SF           False
BB           False
HP           False
KK           False
GD           False
LOB          False
P_HRA_RT     False
P_AB_CN      False
P_HIT_CN     False
OBP          False
OOO          False
win          False
dtype: bool

In [16]:
baseball_data = baseball_data.dropna(axis=0)

In [21]:
baseball_data.info() # 데이터 타입과 전체 몇 경기의 데이터인지 확인

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7288 entries, 0 to 1463
Data columns (total 28 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   G_ID       7288 non-null   object
 1   GDAY_DS    7288 non-null   int64
 2   T_ID       7288 non-null   object
 3   VS_T_ID    7288 non-null   object
 4   HEADER_NO  7288 non-null   int64
 5   TB_SC      7288 non-null   object
 6   PA         7288 non-null   float64
 7   AB         7288 non-null   float64
 8   RBI        7288 non-null   float64
 9   RUN        7288 non-null   float64
 10  HIT        7288 non-null   float64
 11  H2         7288 non-null   int64
 12  H3         7288 non-null   int64
 13  HR         7288 non-null   float64
 14  SB         7288 non-null   int64
 15  CS         7288 non-null   int64
 16  SF         7288 non-null   int64
 17  BB         7288 non-null   float64
 18  HP         7288 non-null   float64
 19  KK         7288 non-null   float64
 20  GD         7288 non-null   float64
 21  LOB        7288 non-null   float64
 22  P_HRA_RT   7288 non-null   float64
 23  P_AB_CN    7288 non-null   int64
 24  P_HIT_CN   7288 non-null   int64
 25  OBP        7288 non-null   float64
 26  OOO        7288 non-null   float64
 27  win        7288 non-null   float64
dtypes: float64(15), int64(9), object(4)
memory usage: 1.6+ MB

In [27]:
# 분석에 필요하다고 생각되는 column으로 df 재구성
baseball_data_re = baseball_data[['T_ID', 'VS_T_ID', 'PA', 'AB', 'RUN', 'OBP', 'OOO', 'win']]
baseball_data_re.head()

  T_ID VS_T_ID    PA    AB   RUN       OBP       OOO  win
0   HH      NE  54.0  42.0   4.0  0.352941  0.238095  0.0
1   NE      HH  46.0  40.0   5.0  0.304348  0.200000  1.0
2   KT      LT  46.0  35.0   9.0  0.511111  0.400000  0.0
3   LT      KT  42.0  37.0  12.0  0.439024  0.378378  1.0
4   LG      HT  34.0  29.0   1.0  0.333333  0.241379  0.0

In [28]:
# 무승부 제거
baseball_data_re = baseball_data_re[baseball_data_re.win != 0.5]

In [29]:
# 무승부가 제거된 경기 수 확인: 7288 경기 중 82 경기 (1.125%)
baseball_data_re.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7206 entries, 0 to 1463
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   T_ID     7206 non-null   object
 1   VS_T_ID  7206 non-null   object
 2   PA       7206 non-null   float64
 3   AB       7206 non-null   float64
 4   RUN      7206 non-null   float64
 5   OBP      7206 non-null   float64
 6   OOO      7206 non-null   float64
 7   win      7206 non-null   float64
dtypes: float64(6), object(2)
memory usage: 506.7+ KB

In [31]:
baseball_data_re['T_ID'].unique()

array(['HH', 'NE', 'KT', 'LT', 'LG', 'HT', 'NC', 'OB', 'SK', 'SS', 'WO'],
      dtype=object)

In [32]:
# NE(넥센)은 WO(키움)으로 변경된 동일한 팀
baseball_data_re = baseball_data_re.replace('NE', 'WO')

In [38]:
# 팀명 한번 더 확인
baseball_data_re['T_ID'].unique() # NE(넥센)이 없어진 걸 확인할 수 있음

array([0, 9, 2, 4, 3, 1, 5, 6, 7, 8], dtype=int64)

In [42]:
# 라벨인코더로 10개 팀 넘버링하기
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(baseball_data_re['T_ID'])
baseball_data_re.loc[:,'T_ID'] = le.transform(baseball_data_re['T_ID'])
baseball_data_re.loc[:,'VS_T_ID'] = le.transform(baseball_data_re['VS_T_ID'])

baseball_data_re.head()

   T_ID  VS_T_ID    PA    AB   RUN       OBP       OOO  win
0     0        9  54.0  42.0   4.0  0.352941  0.238095  0.0
1     9        0  46.0  40.0   5.0  0.304348  0.200000  1.0
2     2        4  46.0  35.0   9.0  0.511111  0.400000  0.0
3     4        2  42.0  37.0  12.0  0.439024  0.378378  1.0
4     3        1  34.0  29.0   1.0  0.333333  0.241379  0.0

In [43]:
baseball_data_re.dtypes
# 데이터 타입을 확인하여 홈팀만 object 타입

T_ID         int64
VS_T_ID      int64
PA         float64
AB         float64
RUN        float64
OBP        float64
OOO        float64
win        float64
dtype: object

In [13]:
# 홈팀(B)은 1로 원정팀(T)는 0으로 변경
baseball_data = baseball_data.replace('T', 0)
baseball_data = baseball_data.replace('B', 1)

In [14]:
baseball_data.head()

,날짜,팀,상대팀,홈팀,타석,타수,타점,득점,안타,홈런,도루,도실,희비,볼넷,삼진,병살,잔루율,출루율,타율,승패
0,20150328,0,9,0,54,42,4,4,10,0,8,0,1,7,7,0,24,0.352941,0.238095,0.0
1,20150328,9,0,1,46,40,5,5,8,2,4,0,0,6,7,1,18,0.304348,0.200000,1.0
2,20150328,2,4,0,46,35,8,9,14,2,2,1,1,8,8,1,23,0.511111,0.400000,0.0
3,20150328,4,2,1,42,37,12,12,14,2,4,1,0,3,8,1,17,0.439024,0.378378,1.0
4,20150328,3,1,0,34,29,1,1,7,0,0,0,0,4,6,2,17,0.333333,0.241379,0.0

In [45]:
print(baseball_data_re.columns)

Index(['T_ID', 'VS_T_ID', 'PA', 'AB', 'RUN', 'OBP', 'OOO', 'win'], dtype='object')

In [46]:
# 승패에 대한 2진 분류를 위해 원핫인코더로 승패를 2개의 column으로 나눈다.
baseball_data_re = pd.get_dummies(baseball_data_re, columns = ['win'])
baseball_data_re.head()

   T_ID  VS_T_ID    PA    AB   RUN       OBP       OOO  win_0.0  win_1.0
0     0        9  54.0  42.0   4.0  0.352941  0.238095        1        0
1     9        0  46.0  40.0   5.0  0.304348  0.200000        0        1
2     2        4  46.0  35.0   9.0  0.511111  0.400000        1        0
3     4        2  42.0  37.0  12.0  0.439024  0.378378        0        1
4     3        1  34.0  29.0   1.0  0.333333  0.241379        1        0

In [47]:
baseball_data_re.info()
# 홈팀은 object에서 int 타입으로 변환이 되었으나, "원핫인코더"를 하면서 승패 colunm에 변화가 생김

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7206 entries, 0 to 1463
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   T_ID     7206 non-null   int64
 1   VS_T_ID  7206 non-null   int64
 2   PA       7206 non-null   float64
 3   AB       7206 non-null   float64
 4   RUN      7206 non-null   float64
 5   OBP      7206 non-null   float64
 6   OOO      7206 non-null   float64
 7   win_0.0  7206 non-null   uint8
 8   win_1.0  7206 non-null   uint8
dtypes: float64(5), int64(2), uint8(2)
memory usage: 464.4 KB

In [49]:
baseball_data_re['win_0.0'] = baseball_data_re['win_0.0'].astype('int')
#baseball_data['승패_0.5'] = baseball_data['승패_0.5'].astype('int')
baseball_data_re['win_1.0'] = baseball_data_re['win_1.0'].astype('int')

In [50]:
# 독립변수, 종속변수
# 위 print(baseball_data.columns)의 index를 이용한다.
data = baseball_data_re[['T_ID', 'VS_T_ID', 'PA', 'AB', 'RUN', 'OBP', 'OOO']]
target = baseball_data_re[['win_0.0', 'win_1.0']] # 무승부는 2진 분류를 위해 위에서 제거하였다.
print(data.shape, target.shape)

(7206, 7) (7206, 2)

In [51]:
# train_x, train_y = train_input, train_target
# test_x, test_y = test_input, test_target

from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(data, target, test_size=0.2, random_state=42)

In [26]:
# train을 이용하여 검증용 sub(진짜 훈련셋)과 val(검증셋)으로 구분하기

sub_x, val_x, sub_y, val_y = train_test_split(train_x, train_y, test_size=0.2, random_state=42)

In [56]:
print(train_x.shape, test_x.shape)
#print(sub_x.shape, val_x.shape)
# 5764개의 train data가 4611개의 sub data와 1153개의 val data로 나누어졌다.

(5764, 7) (1442, 7)

In [57]:
# 모델을 만든다.

X = tf.keras.layers.Input(shape=[7])

H = tf.keras.layers.Dense(10)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(7)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(5)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(2, activation = 'sigmoid')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [53]:
# 모델이 잘 만들어졌는지 확인한다.

model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 15)]              0

 dense (Dense)               (None, 10)                160

 batch_normalization (BatchN  (None, 10)               40
 ormalization)

 activation (Activation)     (None, 10)                0

 dense_1 (Dense)             (None, 7)                 77

 batch_normalization_1 (Batc  (None, 7)                28
 hNormalization)

 activation_1 (Activation)   (None, 7)                 0

 dense_2 (Dense)             (None, 5)                 40

 batch_normalization_2 (Batc  (None, 5)                20
 hNormalization)

 activation_2 (Activation)   (None, 5)                 0

 dense_3 (Dense)             (None, 2)                 12

=================================================================
Total params: 377
Trainable params: 333
Non-trainable params: 44
_________________________________________________________________

In [58]:
# 훈련이 잘 작동하는지 확인해 본다.
model.fit(train_x, train_y, epochs=10)

Epoch 1/10
181/181 [==============================] - 2s 2ms/step - loss: 0.5533 - accuracy: 0.7196
Epoch 2/10
181/181 [==============================] - 0s 2ms/step - loss: 0.4798 - accuracy: 0.7767
Epoch 3/10
181/181 [==============================] - 0s 2ms/step - loss: 0.4596 - accuracy: 0.7824
Epoch 4/10
181/181 [==============================] - 0s 2ms/step - loss: 0.4499 - accuracy: 0.7885
Epoch 5/10
181/181 [==============================] - 0s 2ms/step - loss: 0.4492 - accuracy: 0.7870
Epoch 6/10
181/181 [==============================] - 0s 1ms/step - loss: 0.4420 - accuracy: 0.7878
Epoch 7/10
181/181 [==============================] - 0s 2ms/step - loss: 0.4446 - accuracy: 0.7930
Epoch 8/10
181/181 [==============================] - 0s 2ms/step - loss: 0.4401 - accuracy: 0.7902
Epoch 9/10
181/181 [==============================] - 0s 2ms/step - loss: 0.4399 - accuracy: 0.7920
Epoch 10/10
181/181 [==============================] - 0s 2ms/step - loss: 0.4356 - accuracy: 0.7944

In [59]:
model.fit(train_x, train_y, epochs=100)

Epoch 1/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4341 - accuracy: 0.7958
Epoch 2/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4335 - accuracy: 0.7941
Epoch 3/100
181/181 [==============================] - 0s 1ms/step - loss: 0.4321 - accuracy: 0.7951
Epoch 4/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4282 - accuracy: 0.7977
Epoch 5/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4264 - accuracy: 0.7972
Epoch 6/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4263 - accuracy: 0.8014
Epoch 7/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4212 - accuracy: 0.7984
Epoch 8/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4212 - accuracy: 0.8048
Epoch 9/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4244 - accuracy: 0.8022
Epoch 10/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4201 - accuracy: 0.8034
Epoch 11/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4213 - accuracy: 0.8001
Epoch 12/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4188 - accuracy: 0.8029
Epoch 13/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4149 - accuracy: 0.8053
Epoch 14/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4184 - accuracy: 0.8012
Epoch 15/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4160 - accuracy: 0.8038
Epoch 16/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4210 - accuracy: 0.7960
Epoch 17/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4218 - accuracy: 0.8026
Epoch 18/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4154 - accuracy: 0.8041
Epoch 19/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4167 - accuracy: 0.8085
Epoch 20/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4158 - accuracy: 0.8069
Epoch 21/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4148 - accuracy: 0.8041
Epoch 22/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4118 - accuracy: 0.8017
Epoch 23/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4145 - accuracy: 0.8022
Epoch 24/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4149 - accuracy: 0.8052
Epoch 25/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4147 - accuracy: 0.8014
Epoch 26/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4134 - accuracy: 0.8067
Epoch 27/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4182 - accuracy: 0.8008
Epoch 28/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4126 - accuracy: 0.8055
Epoch 29/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4118 - accuracy: 0.8064
Epoch 30/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4147 - accuracy: 0.8055
Epoch 31/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4140 - accuracy: 0.8020
Epoch 32/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4150 - accuracy: 0.7991
Epoch 33/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4114 - accuracy: 0.8031
Epoch 34/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4158 - accuracy: 0.8033
Epoch 35/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4150 - accuracy: 0.8017
Epoch 36/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4094 - accuracy: 0.8093
Epoch 37/100
181/181 [==============================] - 1s 3ms/step - loss: 0.4119 - accuracy: 0.8008
Epoch 38/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4162 - accuracy: 0.8059
Epoch 39/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4132 - accuracy: 0.8060
Epoch 40/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4123 - accuracy: 0.8031
Epoch 41/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4088 - accuracy: 0.8033
Epoch 42/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4090 - accuracy: 0.8126
Epoch 43/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4112 - accuracy: 0.8057
Epoch 44/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4138 - accuracy: 0.8003
Epoch 45/100
181/181 [==============================] - 1s 3ms/step - loss: 0.4101 - accuracy: 0.8053
Epoch 46/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4177 - accuracy: 0.8019
Epoch 47/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4120 - accuracy: 0.8088
Epoch 48/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4101 - accuracy: 0.8017
Epoch 49/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4116 - accuracy: 0.8045
Epoch 50/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4080 - accuracy: 0.8071
Epoch 51/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4090 - accuracy: 0.8067
Epoch 52/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4076 - accuracy: 0.8064
Epoch 53/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4164 - accuracy: 0.8022
Epoch 54/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4085 - accuracy: 0.8020
Epoch 55/100
181/181 [==============================] - 0s 1ms/step - loss: 0.4085 - accuracy: 0.8095
Epoch 56/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4168 - accuracy: 0.8043
Epoch 57/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4071 - accuracy: 0.8036
Epoch 58/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4093 - accuracy: 0.8090
Epoch 59/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4115 - accuracy: 0.8001
Epoch 60/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4074 - accuracy: 0.8038
Epoch 61/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4076 - accuracy: 0.8062
Epoch 62/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4110 - accuracy: 0.8057
Epoch 63/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4116 - accuracy: 0.8066
Epoch 64/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4068 - accuracy: 0.8128
Epoch 65/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4084 - accuracy: 0.8060
Epoch 66/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4146 - accuracy: 0.8043
Epoch 67/100
181/181 [==============================] - 0s 1ms/step - loss: 0.4079 - accuracy: 0.8043
Epoch 68/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4123 - accuracy: 0.8060
Epoch 69/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4081 - accuracy: 0.8076
Epoch 70/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4183 - accuracy: 0.8041
Epoch 71/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4127 - accuracy: 0.8059
Epoch 72/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4097 - accuracy: 0.7988
Epoch 73/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4107 - accuracy: 0.8062
Epoch 74/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4088 - accuracy: 0.8036
Epoch 75/100
181/181 [==============================] - 0s 3ms/step - loss: 0.4131 - accuracy: 0.8036
Epoch 76/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4059 - accuracy: 0.8073
Epoch 77/100
181/181 [==============================] - 0s 3ms/step - loss: 0.4126 - accuracy: 0.8050
Epoch 78/100
181/181 [==============================] - 0s 3ms/step - loss: 0.4110 - accuracy: 0.7996
Epoch 79/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4071 - accuracy: 0.8073
Epoch 80/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4123 - accuracy: 0.8048
Epoch 81/100

181/181 [==============================] - 0s 2ms/step - loss: 0.4110 - accuracy: 0.8012
Epoch 82/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4090 - accuracy: 0.8041
Epoch 83/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4101 - accuracy: 0.8031
Epoch 84/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4079 - accuracy: 0.8071
Epoch 85/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4097 - accuracy: 0.8046
Epoch 86/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4076 - accuracy: 0.8099
Epoch 87/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4072 - accuracy: 0.8069
Epoch 88/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4095 - accuracy: 0.8005
Epoch 89/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4080 - accuracy: 0.8073
Epoch 90/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4096 - accuracy: 0.8052
Epoch 91/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4092 - accuracy: 0.8046
Epoch 92/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4115 - accuracy: 0.8067
Epoch 93/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4070 - accuracy: 0.8040
Epoch 94/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4065 - accuracy: 0.8078
Epoch 95/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4103 - accuracy: 0.8076
Epoch 96/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4063 - accuracy: 0.8086
Epoch 97/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4043 - accuracy: 0.8045
Epoch 98/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4076 - accuracy: 0.8062
Epoch 99/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4043 - accuracy: 0.8043
Epoch 100/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4098 - accuracy: 0.8019

In [60]:
model.fit(train_x, train_y, epochs=100)#, verbose=0)
# "verbose=0"을 이용해서 훈련과정(fit)을 출력하지 않는다.

Epoch 1/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4051 - accuracy: 0.8085
Epoch 2/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4102 - accuracy: 0.8031
Epoch 3/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4045 - accuracy: 0.8104
Epoch 4/100
181/181 [==============================] - 0s 1ms/step - loss: 0.4069 - accuracy: 0.8052
Epoch 5/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4135 - accuracy: 0.8019
Epoch 6/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4087 - accuracy: 0.8024
Epoch 7/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4074 - accuracy: 0.8048
Epoch 8/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4058 - accuracy: 0.8031
Epoch 9/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4105 - accuracy: 0.8067
Epoch 10/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4060 - accuracy: 0.8045
Epoch 11/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4052 - accuracy: 0.8067
Epoch 12/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4067 - accuracy: 0.8076
Epoch 13/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4105 - accuracy: 0.8071
Epoch 14/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4083 - accuracy: 0.8053
Epoch 15/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4068 - accuracy: 0.8059
Epoch 16/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4030 - accuracy: 0.8053
Epoch 17/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4051 - accuracy: 0.8073
Epoch 18/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4123 - accuracy: 0.7991
Epoch 19/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4057 - accuracy: 0.8059
Epoch 20/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4026 - accuracy: 0.8090
Epoch 21/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4054 - accuracy: 0.8057
Epoch 22/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4074 - accuracy: 0.8027
Epoch 23/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4081 - accuracy: 0.8102
Epoch 24/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4052 - accuracy: 0.8097
Epoch 25/100
181/181 [==============================] - 0s 3ms/step - loss: 0.4076 - accuracy: 0.8062
Epoch 26/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4033 - accuracy: 0.8064
Epoch 27/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4046 - accuracy: 0.8085
Epoch 28/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4076 - accuracy: 0.8040
Epoch 29/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4033 - accuracy: 0.8097
Epoch 30/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4100 - accuracy: 0.8048
Epoch 31/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4044 - accuracy: 0.8093
Epoch 32/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4049 - accuracy: 0.8074
Epoch 33/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4090 - accuracy: 0.8040
Epoch 34/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4091 - accuracy: 0.8067
Epoch 35/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4073 - accuracy: 0.8086
Epoch 36/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4044 - accuracy: 0.8073
Epoch 37/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4038 - accuracy: 0.8095
Epoch 38/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4139 - accuracy: 0.8014
Epoch 39/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4011 - accuracy: 0.8066
Epoch 40/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4087 - accuracy: 0.8024
Epoch 41/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4073 - accuracy: 0.8079
Epoch 42/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4059 - accuracy: 0.8119
Epoch 43/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4025 - accuracy: 0.8069
Epoch 44/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4028 - accuracy: 0.8041
Epoch 45/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4090 - accuracy: 0.8046
Epoch 46/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4109 - accuracy: 0.8067
Epoch 47/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4028 - accuracy: 0.8105
Epoch 48/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4101 - accuracy: 0.8050
Epoch 49/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4024 - accuracy: 0.8073
Epoch 50/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4107 - accuracy: 0.8026
Epoch 51/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4089 - accuracy: 0.8031
Epoch 52/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4020 - accuracy: 0.8086
Epoch 53/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4043 - accuracy: 0.8081
Epoch 54/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4030 - accuracy: 0.8050
Epoch 55/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4049 - accuracy: 0.8086
Epoch 56/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4027 - accuracy: 0.8092
Epoch 57/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4063 - accuracy: 0.8073
Epoch 58/100
181/181 [==============================] - 0s 3ms/step - loss: 0.4060 - accuracy: 0.8093
Epoch 59/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4067 - accuracy: 0.8071
Epoch 60/100
181/181 [==============================] - 0s 1ms/step - loss: 0.4049 - accuracy: 0.8057
Epoch 61/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4074 - accuracy: 0.8066
Epoch 62/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4038 - accuracy: 0.8019
Epoch 63/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4021 - accuracy: 0.8100
Epoch 64/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4077 - accuracy: 0.8060
Epoch 65/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4101 - accuracy: 0.8062
Epoch 66/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4084 - accuracy: 0.8048
Epoch 67/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4072 - accuracy: 0.8017
Epoch 68/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4053 - accuracy: 0.8033
Epoch 69/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4070 - accuracy: 0.8012
Epoch 70/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4098 - accuracy: 0.8038
Epoch 71/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4060 - accuracy: 0.8046
Epoch 72/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4050 - accuracy: 0.8085
Epoch 73/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4055 - accuracy: 0.8036
Epoch 74/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4134 - accuracy: 0.8027
Epoch 75/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4021 - accuracy: 0.8118
Epoch 76/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4035 - accuracy: 0.8052
Epoch 77/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4064 - accuracy: 0.8100
Epoch 78/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3997 - accuracy: 0.8133
Epoch 79/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4056 - accuracy: 0.8109
Epoch 80/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4059 - accuracy: 0.8093
Epoch 81/100

181/181 [==============================] - 0s 2ms/step - loss: 0.4038 - accuracy: 0.8109
Epoch 82/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4024 - accuracy: 0.8107
Epoch 83/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4063 - accuracy: 0.8043
Epoch 84/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4037 - accuracy: 0.8060
Epoch 85/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3995 - accuracy: 0.8073
Epoch 86/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4004 - accuracy: 0.8076
Epoch 87/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4083 - accuracy: 0.8041
Epoch 88/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4042 - accuracy: 0.8008
Epoch 89/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4075 - accuracy: 0.8052
Epoch 90/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4056 - accuracy: 0.8052
Epoch 91/100
181/181 [==============================] - 0s 1ms/step - loss: 0.4079 - accuracy: 0.8041
Epoch 92/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4067 - accuracy: 0.8031
Epoch 93/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4030 - accuracy: 0.8086
Epoch 94/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4104 - accuracy: 0.8046
Epoch 95/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4051 - accuracy: 0.8059
Epoch 96/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4059 - accuracy: 0.8053
Epoch 97/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4034 - accuracy: 0.8048
Epoch 98/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4054 - accuracy: 0.8066
Epoch 99/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4015 - accuracy: 0.8116
Epoch 100/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4049 - accuracy: 0.8066

In [61]:
model.fit(train_x, train_y, epochs=100, verbose=1)

Epoch 1/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4053 - accuracy: 0.8078
Epoch 2/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4035 - accuracy: 0.8088
Epoch 3/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4046 - accuracy: 0.8086
Epoch 4/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4068 - accuracy: 0.8055
Epoch 5/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4034 - accuracy: 0.8090
Epoch 6/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4099 - accuracy: 0.8017
Epoch 7/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4035 - accuracy: 0.8100
Epoch 8/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4052 - accuracy: 0.8074
Epoch 9/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3995 - accuracy: 0.8095
Epoch 10/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4056 - accuracy: 0.8121
Epoch 11/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4090 - accuracy: 0.8071
Epoch 12/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4028 - accuracy: 0.8088
Epoch 13/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4051 - accuracy: 0.8100
Epoch 14/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4070 - accuracy: 0.8114
Epoch 15/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4050 - accuracy: 0.8066
Epoch 16/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4059 - accuracy: 0.8092
Epoch 17/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4044 - accuracy: 0.8088
Epoch 18/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4092 - accuracy: 0.8052
Epoch 19/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4026 - accuracy: 0.8060
Epoch 20/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4054 - accuracy: 0.8074
Epoch 21/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4046 - accuracy: 0.8073
Epoch 22/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4015 - accuracy: 0.8055
Epoch 23/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4023 - accuracy: 0.8085
Epoch 24/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4058 - accuracy: 0.8071
Epoch 25/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4055 - accuracy: 0.8081
Epoch 26/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4054 - accuracy: 0.8055
Epoch 27/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4095 - accuracy: 0.8040
Epoch 28/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4037 - accuracy: 0.8024
Epoch 29/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4022 - accuracy: 0.8066
Epoch 30/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4033 - accuracy: 0.8076
Epoch 31/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4088 - accuracy: 0.8074
Epoch 32/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4063 - accuracy: 0.8052
Epoch 33/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4055 - accuracy: 0.8060
Epoch 34/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4043 - accuracy: 0.8078
Epoch 35/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4081 - accuracy: 0.8052
Epoch 36/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4023 - accuracy: 0.8074
Epoch 37/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4003 - accuracy: 0.8085
Epoch 38/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4022 - accuracy: 0.8102
Epoch 39/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4034 - accuracy: 0.8053
Epoch 40/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4014 - accuracy: 0.8086
Epoch 41/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4137 - accuracy: 0.8060
Epoch 42/100
181/181 [==============================] - 1s 3ms/step - loss: 0.4019 - accuracy: 0.8102
Epoch 43/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4122 - accuracy: 0.8073
Epoch 44/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4016 - accuracy: 0.8045
Epoch 45/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4001 - accuracy: 0.8090
Epoch 46/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4048 - accuracy: 0.8055
Epoch 47/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4057 - accuracy: 0.8086
Epoch 48/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4064 - accuracy: 0.8074
Epoch 49/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4024 - accuracy: 0.8132
Epoch 50/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4026 - accuracy: 0.8102
Epoch 51/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4014 - accuracy: 0.8085
Epoch 52/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4033 - accuracy: 0.8064
Epoch 53/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4028 - accuracy: 0.8121
Epoch 54/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3982 - accuracy: 0.8097
Epoch 55/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3970 - accuracy: 0.8100
Epoch 56/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4072 - accuracy: 0.8050
Epoch 57/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4046 - accuracy: 0.8031
Epoch 58/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4040 - accuracy: 0.8067
Epoch 59/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3980 - accuracy: 0.8112
Epoch 60/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4076 - accuracy: 0.8040
Epoch 61/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4079 - accuracy: 0.8040
Epoch 62/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4027 - accuracy: 0.8059
Epoch 63/100
181/181 [==============================] - 0s 1ms/step - loss: 0.4004 - accuracy: 0.8118
Epoch 64/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4064 - accuracy: 0.8060
Epoch 65/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4023 - accuracy: 0.8040
Epoch 66/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4106 - accuracy: 0.7996
Epoch 67/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4032 - accuracy: 0.8112
Epoch 68/100
181/181 [==============================] - 0s 1ms/step - loss: 0.4065 - accuracy: 0.8048
Epoch 69/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4001 - accuracy: 0.8088
Epoch 70/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4065 - accuracy: 0.8076
Epoch 71/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4099 - accuracy: 0.8088
Epoch 72/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4011 - accuracy: 0.8055
Epoch 73/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4051 - accuracy: 0.8093
Epoch 74/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3989 - accuracy: 0.8171
Epoch 75/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4055 - accuracy: 0.8099
Epoch 76/100
181/181 [==============================] - 0s 3ms/step - loss: 0.4028 - accuracy: 0.8069
Epoch 77/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4062 - accuracy: 0.8046
Epoch 78/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4046 - accuracy: 0.8053
Epoch 79/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4020 - accuracy: 0.8081
Epoch 80/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4016 - accuracy: 0.8026
Epoch 81/100

181/181 [==============================] - 0s 2ms/step - loss: 0.3994 - accuracy: 0.8052
Epoch 82/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4029 - accuracy: 0.8073
Epoch 83/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4068 - accuracy: 0.8078
Epoch 84/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4009 - accuracy: 0.8069
Epoch 85/100
181/181 [==============================] - 0s 1ms/step - loss: 0.3995 - accuracy: 0.8119
Epoch 86/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4017 - accuracy: 0.8076
Epoch 87/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4032 - accuracy: 0.8029
Epoch 88/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4045 - accuracy: 0.8064
Epoch 89/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3994 - accuracy: 0.8107
Epoch 90/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4065 - accuracy: 0.8078
Epoch 91/100
181/181 [==============================] - 0s 1ms/step - loss: 0.4027 - accuracy: 0.8055
Epoch 92/100
181/181 [==============================] - 0s 1ms/step - loss: 0.4010 - accuracy: 0.8069
Epoch 93/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4073 - accuracy: 0.8071
Epoch 94/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4004 - accuracy: 0.8121
Epoch 95/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4023 - accuracy: 0.8076
Epoch 96/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4006 - accuracy: 0.8092
Epoch 97/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4045 - accuracy: 0.8038
Epoch 98/100
181/181 [==============================] - 0s 1ms/step - loss: 0.4034 - accuracy: 0.8074
Epoch 99/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4035 - accuracy: 0.8066
Epoch 100/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4024 - accuracy: 0.8099

In [62]:
model.fit(train_x, train_y, epochs=100, verbose=1)

Epoch 1/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4049 - accuracy: 0.8038
Epoch 2/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4071 - accuracy: 0.8029
Epoch 3/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4028 - accuracy: 0.8085
Epoch 4/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4013 - accuracy: 0.8081
Epoch 5/100
181/181 [==============================] - 0s 1ms/step - loss: 0.4054 - accuracy: 0.8001
Epoch 6/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4025 - accuracy: 0.8081
Epoch 7/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4037 - accuracy: 0.8085
Epoch 8/100
181/181 [==============================] - 0s 1ms/step - loss: 0.4018 - accuracy: 0.8085
Epoch 9/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4034 - accuracy: 0.8102
Epoch 10/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4074 - accuracy: 0.8073
Epoch 11/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4032 - accuracy: 0.8060
Epoch 12/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3997 - accuracy: 0.8105
Epoch 13/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4024 - accuracy: 0.8074
Epoch 14/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3974 - accuracy: 0.8114
Epoch 15/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4056 - accuracy: 0.8017
Epoch 16/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4032 - accuracy: 0.8123
Epoch 17/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3984 - accuracy: 0.8111
Epoch 18/100
181/181 [==============================] - 1s 3ms/step - loss: 0.4079 - accuracy: 0.8024
Epoch 19/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4075 - accuracy: 0.8066
Epoch 20/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4009 - accuracy: 0.8107
Epoch 21/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4008 - accuracy: 0.8067
Epoch 22/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3976 - accuracy: 0.8099
Epoch 23/100
181/181 [==============================] - 0s 3ms/step - loss: 0.4032 - accuracy: 0.8102
Epoch 24/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4016 - accuracy: 0.8045
Epoch 25/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4014 - accuracy: 0.8092
Epoch 26/100
181/181 [==============================] - 0s 3ms/step - loss: 0.4065 - accuracy: 0.8046
Epoch 27/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4034 - accuracy: 0.8055
Epoch 28/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4010 - accuracy: 0.8060
Epoch 29/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4049 - accuracy: 0.8043
Epoch 30/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4016 - accuracy: 0.8119
Epoch 31/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4041 - accuracy: 0.8081
Epoch 32/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4041 - accuracy: 0.8079
Epoch 33/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3989 - accuracy: 0.8059
Epoch 34/100
181/181 [==============================] - 1s 3ms/step - loss: 0.4022 - accuracy: 0.8107
Epoch 35/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3974 - accuracy: 0.8112
Epoch 36/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4065 - accuracy: 0.8014
Epoch 37/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4007 - accuracy: 0.8111
Epoch 38/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3992 - accuracy: 0.8079
Epoch 39/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3992 - accuracy: 0.8086
Epoch 40/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3972 - accuracy: 0.8079
Epoch 41/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3963 - accuracy: 0.8111
Epoch 42/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4009 - accuracy: 0.8078
Epoch 43/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4036 - accuracy: 0.8133
Epoch 44/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3997 - accuracy: 0.8027
Epoch 45/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4034 - accuracy: 0.8086
Epoch 46/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4008 - accuracy: 0.8050
Epoch 47/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3964 - accuracy: 0.8114
Epoch 48/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3998 - accuracy: 0.8066
Epoch 49/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4027 - accuracy: 0.8069
Epoch 50/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4012 - accuracy: 0.8111
Epoch 51/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4047 - accuracy: 0.8057
Epoch 52/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4059 - accuracy: 0.8090
Epoch 53/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3996 - accuracy: 0.8095
Epoch 54/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4015 - accuracy: 0.8073
Epoch 55/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4023 - accuracy: 0.8040
Epoch 56/100
181/181 [==============================] - 1s 3ms/step - loss: 0.4019 - accuracy: 0.8053
Epoch 57/100
181/181 [==============================] - 0s 1ms/step - loss: 0.3993 - accuracy: 0.8112
Epoch 58/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3992 - accuracy: 0.8083
Epoch 59/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4007 - accuracy: 0.8097
Epoch 60/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4016 - accuracy: 0.8036
Epoch 61/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4059 - accuracy: 0.8071
Epoch 62/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4068 - accuracy: 0.8092
Epoch 63/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4018 - accuracy: 0.8090
Epoch 64/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4017 - accuracy: 0.8060
Epoch 65/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4004 - accuracy: 0.8099
Epoch 66/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4003 - accuracy: 0.8083
Epoch 67/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4055 - accuracy: 0.8059
Epoch 68/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4025 - accuracy: 0.8102
Epoch 69/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3988 - accuracy: 0.8086
Epoch 70/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4065 - accuracy: 0.8071
Epoch 71/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4016 - accuracy: 0.8062
Epoch 72/100
181/181 [==============================] - 0s 1ms/step - loss: 0.3993 - accuracy: 0.8119
Epoch 73/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4017 - accuracy: 0.8043
Epoch 74/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3998 - accuracy: 0.8059
Epoch 75/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4027 - accuracy: 0.8105
Epoch 76/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3979 - accuracy: 0.8145
Epoch 77/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4012 - accuracy: 0.8107
Epoch 78/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4021 - accuracy: 0.8071
Epoch 79/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4014 - accuracy: 0.8083
Epoch 80/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3999 - accuracy: 0.8090
Epoch 81/100

181/181 [==============================] - 0s 2ms/step - loss: 0.4062 - accuracy: 0.8041
Epoch 82/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4055 - accuracy: 0.8041
Epoch 83/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4017 - accuracy: 0.8114
Epoch 84/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4039 - accuracy: 0.8095
Epoch 85/100
181/181 [==============================] - 0s 1ms/step - loss: 0.4025 - accuracy: 0.8073
Epoch 86/100
181/181 [==============================] - 0s 1ms/step - loss: 0.3974 - accuracy: 0.8060
Epoch 87/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4053 - accuracy: 0.8062
Epoch 88/100
181/181 [==============================] - 0s 1ms/step - loss: 0.4017 - accuracy: 0.8088
Epoch 89/100
181/181 [==============================] - 0s 1ms/step - loss: 0.4053 - accuracy: 0.8073
Epoch 90/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4039 - accuracy: 0.8052
Epoch 91/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4028 - accuracy: 0.8064
Epoch 92/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3975 - accuracy: 0.8092
Epoch 93/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3937 - accuracy: 0.8073
Epoch 94/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4026 - accuracy: 0.8093
Epoch 95/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4018 - accuracy: 0.8085
Epoch 96/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4001 - accuracy: 0.8073
Epoch 97/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3960 - accuracy: 0.8086
Epoch 98/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3983 - accuracy: 0.8053
Epoch 99/100
181/181 [==============================] - 0s 2ms/step - loss: 0.4020 - accuracy: 0.8095
Epoch 100/100
181/181 [==============================] - 0s 2ms/step - loss: 0.3950 - accuracy: 0.8133

In [65]:
model.fit(train_x, train_y, epochs=10, verbose=1)

Epoch 1/10
181/181 [==============================] - 0s 2ms/step - loss: 0.3970 - accuracy: 0.8109
Epoch 2/10
181/181 [==============================] - 0s 2ms/step - loss: 0.3963 - accuracy: 0.8123
Epoch 3/10
181/181 [==============================] - 0s 2ms/step - loss: 0.4005 - accuracy: 0.8125
Epoch 4/10
181/181 [==============================] - 0s 2ms/step - loss: 0.3948 - accuracy: 0.8086
Epoch 5/10
181/181 [==============================] - 0s 2ms/step - loss: 0.3923 - accuracy: 0.8144
Epoch 6/10
181/181 [==============================] - 0s 2ms/step - loss: 0.3960 - accuracy: 0.8138
Epoch 7/10
181/181 [==============================] - 0s 3ms/step - loss: 0.3961 - accuracy: 0.8112
Epoch 8/10
181/181 [==============================] - 0s 2ms/step - loss: 0.3994 - accuracy: 0.8079
Epoch 9/10
181/181 [==============================] - 0s 2ms/step - loss: 0.3933 - accuracy: 0.8109
Epoch 10/10
181/181 [==============================] - 0s 2ms/step - loss: 0.3964 - accuracy: 0.8137

In [69]:
print(model.predict(test_x[0:10]))
print(test_y[0:10])

1/1 [==============================] - 0s 186ms/step
[[0.38595366 0.37115294]
 [0.7620071  0.18430448]
 [0.45416173 0.53308815]
 [0.54945475 0.55299544]
 [0.3623237  0.7230705 ]
 [0.38480023 0.6268317 ]
 [0.6099422  0.4606175 ]
 [0.03653229 0.7241401 ]
 [0.37760687 0.73690236]
 [0.72141135 0.20109823]]
      win_0.0  win_1.0
223         0        1
111         1        0
582         0        1
177         1        0
230         0        1
1214        1        0
660         1        0
1147        0        1
1242        0        1
752         1        0

In [70]:
model.evaluate(test_x, test_y)

46/46 [==============================] - 0s 1ms/step - loss: 0.4103 - accuracy: 0.7954

[0.41026291251182556, 0.7954230308532715]